//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Captone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coach
    {
        public Coach()
        {
            this.Schedules = new HashSet<Schedule>();
        }
    
        public int CoachID { get; set; }
        public string NumberPlate { get; set; }
        public int CoachTypeID { get; set; }
    
        public virtual CoachType CoachType { get; set; }
        public virtual ICollection<Schedule> Schedules { get; set; }
    }
}
