//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Captone.Repositories.Interfaces;

namespace Captone.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iDeliverEntities : DbContext, IUnitOfWork
    {
        public iDeliverEntities()
            : base("name=iDeliverEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<Assigning> Assignings { get; set; }
        public DbSet<Coach> Coaches { get; set; }
        public DbSet<CoachType> CoachTypes { get; set; }
        public DbSet<Comment> Comments { get; set; }
        public DbSet<DeliveryStatu> DeliveryStatus { get; set; }
        public DbSet<Invoice> Invoices { get; set; }
        public DbSet<ManageFee> ManageFees { get; set; }
        public DbSet<Notification> Notifications { get; set; }
        public DbSet<Province> Provinces { get; set; }
        public DbSet<Rating> Ratings { get; set; }
        public DbSet<Request> Requests { get; set; }
        public DbSet<Route> Routes { get; set; }
        public DbSet<RouteStage> RouteStages { get; set; }
        public DbSet<Schedule> Schedules { get; set; }
        public DbSet<Stage> Stages { get; set; }
        public DbSet<Station> Stations { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Trip> Trips { get; set; }
        public DbSet<UserInfo> UserInfoes { get; set; }
        public void SaveChanges()
        {
            base.SaveChanges();
        }
    }
}
