//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Captone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public Request()
        {
            this.Assignings = new HashSet<Assigning>();
            this.Invoices = new HashSet<Invoice>();
        }
    
        public int RequestID { get; set; }
        public string Username { get; set; }
        public int DeliveryStatusID { get; set; }
        public int FeeID { get; set; }
        public string EstimateWeight { get; set; }
        public string EstimateVolume { get; set; }
        public System.DateTime DateRequest { get; set; }
        public int FromLocation { get; set; }
        public int ToLocation { get; set; }
        public string SenderName { get; set; }
        public string SenderAddress { get; set; }
        public string ReceiverAddress { get; set; }
        public string SenderPhone { get; set; }
        public string ReceiverName { get; set; }
        public string ReceiverPhone { get; set; }
        public bool Type { get; set; }
        public string TypeOfPayment { get; set; }
        public Nullable<System.DateTime> ArrivedDate { get; set; }
        public bool Payment { get; set; }
        public string RequestCode { get; set; }
        public double Length { get; set; }
        public double Width { get; set; }
        public double Height { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<Assigning> Assignings { get; set; }
        public virtual DeliveryStatu DeliveryStatu { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ManageFee ManageFee { get; set; }
        public virtual Station Station { get; set; }
        public virtual Station Station1 { get; set; }
    }
}
