//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Captone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public Route()
        {
            this.CoachArrangements = new HashSet<CoachArrangement>();
            this.RouteStages = new HashSet<RouteStage>();
            this.Trips = new HashSet<Trip>();
        }
    
        public int RouteID { get; set; }
        public string RouteName { get; set; }
        public Nullable<double> Container { get; set; }
    
        public virtual ICollection<CoachArrangement> CoachArrangements { get; set; }
        public virtual ICollection<RouteStage> RouteStages { get; set; }
        public virtual ICollection<Trip> Trips { get; set; }
    }
}
