//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Captone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public Route()
        {
            this.RouteStages = new HashSet<RouteStage>();
            this.Schedules = new HashSet<Schedule>();
        }
    
        public int RouteID { get; set; }
        public string RouteName { get; set; }
        public double Container { get; set; }
    
        public virtual ICollection<RouteStage> RouteStages { get; set; }
        public virtual ICollection<Schedule> Schedules { get; set; }
    }
}
