//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Captone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station
    {
        public Station()
        {
            this.Accounts = new HashSet<Account>();
            this.Assignings = new HashSet<Assigning>();
            this.Comments = new HashSet<Comment>();
            this.Notifications = new HashSet<Notification>();
            this.Ratings = new HashSet<Rating>();
            this.Requests = new HashSet<Request>();
            this.Requests1 = new HashSet<Request>();
            this.Stages = new HashSet<Stage>();
            this.Stages1 = new HashSet<Stage>();
        }
    
        public int StationID { get; set; }
        public string StationName { get; set; }
        public string StationLocation { get; set; }
        public string StationPhone { get; set; }
        public string Coordinate { get; set; }
        public int ProvinceID { get; set; }
        public Nullable<double> AvgRatingLevel { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<Assigning> Assignings { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual Province Province { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<Request> Requests { get; set; }
        public virtual ICollection<Request> Requests1 { get; set; }
        public virtual ICollection<Stage> Stages { get; set; }
        public virtual ICollection<Stage> Stages1 { get; set; }
    }
}
