//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Captone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public Trip()
        {
            this.Assignings = new HashSet<Assigning>();
        }
    
        public int TripID { get; set; }
        public System.DateTime EstimateDepartureTime { get; set; }
        public System.DateTime EstimateArrivalTime { get; set; }
        public Nullable<System.DateTime> RealDepartureTime { get; set; }
        public Nullable<System.DateTime> RealArrivalTime { get; set; }
        public double EstimateVolume { get; set; }
        public Nullable<double> AvailableVolume { get; set; }
        public Nullable<double> RealVolume { get; set; }
        public int ScheduleID { get; set; }
        public bool IsActive { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Assigning> Assignings { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
