//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Captone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public int StationID { get; set; }
        public bool isView { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Station Station { get; set; }
    }
}
