//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Captone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assigning
    {
        public int TripID { get; set; }
        public int RequestID { get; set; }
        public Nullable<int> IndicateOrder { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
    
        public virtual Request Request { get; set; }
        public virtual Trip Trip { get; set; }
    }
}
