//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Captone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoachType
    {
        public CoachType()
        {
            this.Coaches = new HashSet<Coach>();
        }
    
        public int CoachTypeID { get; set; }
        public int Seats { get; set; }
        public Nullable<double> Capacity { get; set; }
    
        public virtual ICollection<Coach> Coaches { get; set; }
    }
}
