//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Captone.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class CoachType
    {
        public CoachType()
        {
            this.Coaches = new HashSet<Coach>();
        }
    
        public int CoachTypeID { get; set; }
        [Required]
        [RegularExpression(@"^[0-9]{2}$")]
        [StringLength(2)]
        [Range(10, 55)]
        [DisplayName("Số ghế ngồi")]
        public int Seats { get; set; }
        [RegularExpression(@"^\d{1}\.\d{2}$")]
        [DisplayName("Thể tích khoang chứa hàng")]
        public Nullable<double> Capacity { get; set; }
    
        public virtual ICollection<Coach> Coaches { get; set; }
    }
}
