//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Captone.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Coach
    {
        public Coach()
        {
            this.Trips = new HashSet<Trip>();
        }
    
        public int CoachID { get; set; }
        [Required]
        [DisplayName("Biển số xe")]
        public string NumberPlate { get; set; }
        [DisplayName("Tuyến")]
        public Nullable<int> RouteID { get; set; }
        [DisplayName("Loại xe")]
        [Required]
        public int CoachTypeID { get; set; }
    
        public virtual CoachType CoachType { get; set; }
        public virtual ICollection<Trip> Trips { get; set; }
    }
}
