//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Captone.Repositories.Interfaces;

namespace Captone.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class iDeliverEntities : DbContext, IUnitOfWork
    {
        public iDeliverEntities()
            : base("name=iDeliverEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Account { get; set; }
        public DbSet<Assigning> Assigning { get; set; }
        public DbSet<Coach> Coach { get; set; }
        public DbSet<CoachType> CoachType { get; set; }
        public DbSet<Comment> Comment { get; set; }
        public DbSet<DeliveryStatus> DeliveryStatus { get; set; }
        public DbSet<Invoice> Invoice { get; set; }
        public DbSet<ManageFee> ManageFee { get; set; }
        public DbSet<Rating> Rating { get; set; }
        public DbSet<Request> Request { get; set; }
        public DbSet<Route> Route { get; set; }
        public DbSet<Station> Station { get; set; }
        public DbSet<Trip> Trip { get; set; }
        public DbSet<UserInfo> UserInfo { get; set; }
        public DbSet<Volume> Volume { get; set; }

        void IUnitOfWork.SaveChanges()
        {
            base.SaveChanges();
        }
    }
}
