//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Captone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManageFee
    {
        public ManageFee()
        {
            this.Invoice = new HashSet<Invoice>();
            this.Request = new HashSet<Request>();
        }
    
        public int FeeID { get; set; }
        public double Fee { get; set; }
        public double MinWeight { get; set; }
        public double MaxWeight { get; set; }
        public double MinVolume { get; set; }
        public double MaxVolume { get; set; }
    
        public virtual ICollection<Invoice> Invoice { get; set; }
        public virtual ICollection<Request> Request { get; set; }
    }
}
