//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Captone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int RatingID { get; set; }
        public string Username { get; set; }
        public int RateLevel { get; set; }
        public int RouteID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Route Route { get; set; }
    }
}
