//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Captone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public Request()
        {
            this.Assigning = new HashSet<Assigning>();
            this.Invoice = new HashSet<Invoice>();
        }
    
        public int RequestID { get; set; }
        public string Username { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> FeeID { get; set; }
        public Nullable<double> EstimateWeight { get; set; }
        public Nullable<double> EstimateVolume { get; set; }
        public System.DateTime DateRequest { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public int FromLocation { get; set; }
        public int ToLocation { get; set; }
        public string SenderAddress { get; set; }
        public string ReceiverAddress { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<Assigning> Assigning { get; set; }
        public virtual DeliveryStatus DeliveryStatus { get; set; }
        public virtual ICollection<Invoice> Invoice { get; set; }
        public virtual ManageFee ManageFee { get; set; }
        public virtual Station Station { get; set; }
        public virtual Station Station1 { get; set; }
    }
}
