//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Captone.Models
{
    using System;
    using System.Collections.Generic;
using System.ComponentModel;
    
    public partial class Route
    {
        public Route()
        {
            this.Trips = new HashSet<Trip>();
        }
    
        public int RouteID { get; set; }
        [DisplayName("Tên tuyến")]
        public string RouteName { get; set; }
        [DisplayName("Trạm đầu")]
        public int StartPoint { get; set; }
        [DisplayName("Trạm cuối")]
        public int EndPoint { get; set; }
        [DisplayName("Điểm đánh giá")]
        public Nullable<double> AvgRateLevel { get; set; }
        [DisplayName("Thời gian xe chạy dự kiến")]
        public Nullable<double> Duration { get; set; }
        [DisplayName("Độ dài tuyến")]
        public Nullable<double> Distance { get; set; }
        [DisplayName("Tải trọng")]
        public Nullable<double> Container { get; set; }
    
        public virtual Station Station { get; set; }
        public virtual Station Station1 { get; set; }
        public virtual ICollection<Trip> Trips { get; set; }
    }
}
