//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Captone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public Route()
        {
            this.Schedules = new HashSet<Schedule>();
            this.Trips = new HashSet<Trip>();
        }
    
        public int RouteID { get; set; }
        public string RouteName { get; set; }
        public int StartPoint { get; set; }
        public int EndPoint { get; set; }
        public Nullable<double> Duration { get; set; }
        public Nullable<double> Distance { get; set; }
        public Nullable<double> Container { get; set; }
    
        public virtual Station Station { get; set; }
        public virtual ICollection<Schedule> Schedules { get; set; }
        public virtual Station Station1 { get; set; }
        public virtual ICollection<Trip> Trips { get; set; }
    }
}
