//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Captone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public Route()
        {
            this.Comment = new HashSet<Comment>();
            this.Rating = new HashSet<Rating>();
            this.Trip = new HashSet<Trip>();
            this.Volume = new HashSet<Volume>();
        }
    
        public string RouteID { get; set; }
        public string RouteName { get; set; }
        public Nullable<int> StartPoint { get; set; }
        public Nullable<int> EndPoint { get; set; }
        public Nullable<double> AvgRateLevel { get; set; }
        public Nullable<int> CoachID { get; set; }
        public Nullable<double> Duration { get; set; }
        public Nullable<double> Distance { get; set; }
    
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ICollection<Rating> Rating { get; set; }
        public virtual Station Station { get; set; }
        public virtual Station Station1 { get; set; }
        public virtual ICollection<Trip> Trip { get; set; }
        public virtual ICollection<Volume> Volume { get; set; }
    }
}
