//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Captone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station
    {
        public Station()
        {
            this.Request = new HashSet<Request>();
            this.Request1 = new HashSet<Request>();
            this.Route = new HashSet<Route>();
            this.Route1 = new HashSet<Route>();
        }
    
        public int StationID { get; set; }
        public string StationName { get; set; }
        public string StationLocation { get; set; }
        public Nullable<double> BreakTime { get; set; }
        public string StationPhone { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Request> Request { get; set; }
        public virtual ICollection<Request> Request1 { get; set; }
        public virtual ICollection<Route> Route { get; set; }
        public virtual ICollection<Route> Route1 { get; set; }
    }
}
