//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Captone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station
    {
        public Station()
        {
            this.Comments = new HashSet<Comment>();
            this.Ratings = new HashSet<Rating>();
            this.Requests = new HashSet<Request>();
            this.Requests1 = new HashSet<Request>();
            this.Routes = new HashSet<Route>();
            this.Routes1 = new HashSet<Route>();
        }
    
        public int StationID { get; set; }
        public string StationName { get; set; }
        public string StationLocation { get; set; }
        public Nullable<double> BreakTime { get; set; }
        public string StationPhone { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<Request> Requests { get; set; }
        public virtual ICollection<Request> Requests1 { get; set; }
        public virtual ICollection<Route> Routes { get; set; }
        public virtual ICollection<Route> Routes1 { get; set; }
    }
}
