//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Captone.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Trip
    {
        public Trip()
        {
            this.Assignings = new HashSet<Assigning>();
        }
    
        public int TripID { get; set; }
        [DisplayName("Giờ xuất phát dự kiến")]
        public Nullable<System.TimeSpan> EstimateDepartureTime { get; set; }
        [DisplayName("Giờ đến dự kiến")]
        public Nullable<System.TimeSpan> EstimateArrivalTime { get; set; }
        [DisplayName("Giờ khởi hành")]
        public Nullable<System.TimeSpan> RealDepartureTime { get; set; }
        [DisplayName("Giờ đến")]
        public Nullable<System.TimeSpan> RealArrivalTime { get; set; }
        [DisplayName("Thể tích khoang chứa hàng cực đại")]
        public Nullable<double> EstimateVolume { get; set; }
        [DisplayName("Thể tích khoang để chứa hàng")]
        public Nullable<double> AvailableVolume { get; set; }
        [DisplayName("Thể tích khoang chứa hàng còn lại")]
        public Nullable<double> RealVolume { get; set; }
        [DisplayName("Ngày đi")]
        public System.DateTime Date { get; set; }
        [DisplayName("Tuyến")]
        public int RouteID { get; set; }
        [DisplayName("Xe")]
        public int CoachID { get; set; }
    
        public virtual ICollection<Assigning> Assignings { get; set; }
        public virtual Coach Coach { get; set; }
        public virtual Route Route { get; set; }
    }
}
