//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Captone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public Trip()
        {
            this.Assignings = new HashSet<Assigning>();
        }
    
        public int TripID { get; set; }
        public Nullable<System.TimeSpan> EstimateDepartureTime { get; set; }
        public Nullable<System.TimeSpan> EstimateArrivalTime { get; set; }
        public Nullable<System.TimeSpan> RealDepartureTime { get; set; }
        public Nullable<System.TimeSpan> RealArrivalTime { get; set; }
        public Nullable<double> AvailableVolume { get; set; }
        public System.DateTime Date { get; set; }
        public string RouteID { get; set; }
        public int CoachID { get; set; }
    
        public virtual ICollection<Assigning> Assignings { get; set; }
        public virtual Coach Coach { get; set; }
        public virtual Route Route { get; set; }
    }
}
