//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Captone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Volume
    {
        public int VolumeID { get; set; }
        public Nullable<double> MaxVolume { get; set; }
        public Nullable<double> MinVolume { get; set; }
        public string RouteID { get; set; }
        public int CoachTypeID { get; set; }
    
        public virtual CoachType CoachType { get; set; }
        public virtual Route Route { get; set; }
    }
}
