//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Captone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoachArrangement
    {
        public CoachArrangement()
        {
            this.Schedules = new HashSet<Schedule>();
        }
    
        public int ArrangeID { get; set; }
        public Nullable<int> CoachID { get; set; }
        public Nullable<int> RouteID { get; set; }
    
        public virtual Coach Coach { get; set; }
        public virtual Route Route { get; set; }
        public virtual ICollection<Schedule> Schedules { get; set; }
    }
}
