//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Captone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public Route()
        {
            this.CoachArrangements = new HashSet<CoachArrangement>();
        }
    
        public int RouteID { get; set; }
        public string RouteName { get; set; }
        public int StartPoint { get; set; }
        public int EndPoint { get; set; }
        public Nullable<System.TimeSpan> BreakTime { get; set; }
        public double Duration { get; set; }
        public double Distance { get; set; }
        public double Container { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual ICollection<CoachArrangement> CoachArrangements { get; set; }
        public virtual Station Station { get; set; }
        public virtual Station Station1 { get; set; }
    }
}
